language: go
go:
    - 1.8
before_script:
    - go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
    - go get github.com/PuerkitoBio/goquery
    - go get github.com/pkg/browser
    - go get github.com/Baozisoftware/qrcode-terminal-go
    - go get github.com/mattn/go-isatty
    - go get github.com/tcnksm/ghr
script:
    - cd $HOME/gopath/src/github.com/Baozisoftware/luzhibo
    - chmod +x ./make.sh
    - ./make.sh
    - ghr --u Baozisoftware --t $GITHUB_TOKEN --v "Ver `cat ver`" --b `cat changelog` --recreate latest releases/
    - exit 0
