language: go
go:
    - 1.8
before_script:
    - go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
    - go get github.com/PuerkitoBio/goquery
    - go get github.com/pkg/browser
    - go get github.com/Baozisoftware/qrcode-terminal-go
    - go get github.com/mattn/go-isatty
    - go get github.com/tcnksm/ghr
    - go get github.com/aktau/github-release
script:
    - cd $HOME/gopath/src/github.com/Baozisoftware/luzhibo
    - chmod +x ./make.sh
    - ./make.sh
    - ghr -u Baozisoftware -t $GITHUB_TOKEN -replace latest releases/
    - github-release edit -u Baozisoftware -s $GITHUB_TOKEN -r luzhibo -t latest -n "Ver `cat ver`" -d "`cat changelog`"
    - $ curl -H "Content-Type: application/json" --data '{"docker_tag": "$DOCKER_TAG"}' -X POST https://registry.hub.docker.com/u/$DOCKER_USER/DOCKER_REPO/trigger/$DOCKER_TRIGGER_TOKEN/
    - exit 0
notifications:
    email: false
