language: go
go:
    - 1.8
before_script:
    - go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
    - go get github.com/PuerkitoBio/goquery
    - go get github.com/pkg/browser
    - go get github.com/Baozisoftware/qrcode-terminal-go
    - go get github.com/mattn/go-isatty
    - go get github.com/tcnksm/ghr
    - go get github.com/aktau/github-release
script:
    - cd $HOME/gopath/src/github.com/Baozisoftware/luzhibo
    - chmod +x ./make.sh
    - ./make.sh
    - ghr -u Baozisoftware -t $GITHUB_TOKEN -recreate latest releases/
    - github-release edit -u Baozisoftware -s $GITHUB_TOKEN -r luzhibo -t latest -n "Ver `cat ver`" -d "`cat changelog`"
    - exit 0
notifications:
    email: false
